CREATE PROCEDURE AddCascadeToSCards
AS
BEGIN
    SET NOCOUNT ON;
    ALTER TABLE S_Cards DROP CONSTRAINT FK_S_Cards_Book
    ALTER TABLE T_Cards DROP CONSTRAINT FK_T_Cards_Book

    ALTER TABLE S_Cards
    ADD CONSTRAINT FK_SCards_Books
    FOREIGN KEY (Id_Book) REFERENCES Books(Id)
    ON DELETE CASCADE;
    ALTER TABLE T_Cards
    ADD CONSTRAINT FK_SCards_Books
    FOREIGN KEY (Id_Book) REFERENCES Books(Id)
    ON DELETE CASCADE;
END
GO

DROP PROCEDURE AddCascadeToSCards
